FROM  python:3.8.13-bullseye

ENV PYTHONUNBUFFERED=1

WORKDIR /api

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# copy from the current directory of the Dockerfile to /api in the image
COPY . . 
EXPOSE 8000

# Start the application when the container launches
CMD ["sh", "./docker-entrypoint.sh"]